name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

target-branch: develop

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚙️ Refactoring'
    labels:
      - 'refactor'
  - title: '💨 Performance Improvements'
    labels:
      - 'performance'
      - 'perf'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'build'
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'major'
    collapse-after: 1

change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
      - 'docs'
      - 'refactor'
      - 'performance'
      - 'test'
      - 'chore'
  default: patch

template: |
  ## 🌟 Summary


  ## 📊 Key Changes


  ## 🎯 Purpose & Impact


  ## What's Changed

  $CHANGES

# 🏷️ Inline autolabeler configuration
autolabeler:
  - label: 'feature'
    title:
      - '^feat'
      - '^feature'
  - label: 'fix'
    title:
      - '^fix'
      - '^bug'
  - label: 'docs'
    title:
      - '^docs'
      - '^documentation'
  - label: 'refactor'
    title:
      - '^refactor'
  - label: 'test'
    title:
      - '^test'
      - '^tests'
  - label: 'chore'
    title:
      - '^chore'
      - '^build'
  - label: 'performance'
    title:
      - '^perf'
      - '^performance'
  - label: 'breaking'
    title:
      - '!'
